### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by kopax** [haiwen/seafile-docker#1]
docker-compose && Dockerfile missing

**Comment by Kidswiss** [comment]
+1

**Comment by foxel** [comment]
Hi.

How about adopting https://github.com/foxel/seafile-docker ? ;)

**Comment by kopax** [comment]
Is it data persistent ? I had some problem restoring seafile when moving hosts.

**Comment by foxel** [comment]
@kopax, yes, the date is persistent inside volume.
See docker documentation for how to move volumes between hosts.

**Comment by kopax** [comment]
@foxel I would be happy to have a try now,

Could you add some more details : 

eg  :

- data persistence volumes
- how to perform safe backup
- how to perform safe restore
- how to perform safe upgrade

**Comment by foxel** [comment]
@kopax

Container uses named persistent volumes.
For backup and restore routines please see http://manual.seafile.com/maintain/backup_recovery.html and https://docs.docker.com/engine/tutorials/dockervolumes/#/backup-restore-or-migrate-data-volumes

Upgrade instructions rely on seafile general update instructions. And if this docker container will require any extra action information will be added as new versions are added.
