### ISSUE TITLE
latest link pointing to wrong directory

### ISSUE THREAD

**Issue by Tahvok** [haiwen/seafile-docker#104]
I have upgraded yesterday, and upon browsing all css/js files returned 404. So I've checked it, and to my surprise, the latest symlink was pointing to incorrect version:
```
# ls -lah /opt/seafile/seafile-server-latest 
lrwxrwxrwx 1 root root 33 Sep  8 12:33 /opt/seafile/seafile-server-latest -> /opt/seafile/seafile-server-6.3.2
```
However 6.3.2 is incorrect, it should be 6.3.3.

The fix was simple, but shouldn't it be part of the docker image already?

Also, as we are using a docker image, there is no benefit at all to use the "latest" symlink - simply deploy the latest version into the latest directory directly.

**Comment by lins05** [comment]
There is a bug in the auto upgrade code which should detect minor upgrades and auto-run the minor upgrade script. I'll fix it soon. Thanks for reporting!
