### ISSUE TITLE
Docker support for aarch64

### ISSUE THREAD

**Issue by axeII** [haiwen/seafile-docker#108]
Are you guys planning to add support for aarch64/arm64 architecture? It would be awesome to have one. 🙏 

Thanks in advance.

**Comment by shoeper** [comment]
So far there is not even an arm64 release afaik.

Could be build on e.g. [scaleway](https://www.scaleway.com/virtual-cloud-servers/#anchor_arm), though, in case an arm server is needed.

**Comment by Poincare1** [comment]
I am also looking for an ARM64 server setup.  I can't find binaries or source files for compilation.  Do they exist?
