### ISSUE TITLE
Add EXPOSE 80 in Dockerfile

### ISSUE THREAD

**Issue by tonito659** [haiwen/seafile-docker#109]
Hi ! I'm using Seafile behind jwilder/nginx-proxy. This container binds to the docker socket and scans running containers to facilitate reverse-proxying them. 
But to automate it, it needs to know which ports are exposed by the container. Thoses ports are defined while building the image using EXPOSE (port number)

In addition this is good practice as it can help building on top of an image.

**Comment by ohrensessel** [comment]
As EXPOSE is given in the dockerfile of the pro version, I do not see any reason why it shouldn't be present in the normal version? came accross issue #28 and was wondering why it hasn't been merged...

**Comment by freeplant** [comment]
Fixed in https://github.com/haiwen/seafile-docker/pull/143

**Comment by tonito659** [comment]
Thanks a lot !
