### ISSUE TITLE
installation process does not work for SELinux enabled host

### ISSUE THREAD

**Issue by joukhaha** [haiwen/seafile-docker#11]
The present version of the installer does not appear to support installation on SELinux enabled hosts.

To enable installation I needed to edit the launcher script to include the option :Z for each volume mount (e.g. -v ${dockerdir}/scripts:/scripts:Z or $dockerdir/scripts:/scripts:ro,Z in case :ro was already used) as instructed in http://stackoverflow.com/questions/24288616/permission-denied-on-accessing-host-directory-in-docker. 

((In addition, to disable checking launcher overwrites upon each container rebuild I also needed to replace for now the line
\#    if [[ "e$(git symbolic-ref --short HEAD)" == "master" ]]; then
with
   if [[ "e$(git symbolic-ref --short HEAD)" == "masteriii" ]]; then
in the rebuild() function in launcher ))

Would it be possible to include the :Z (or :ro,Z) flag by default in the launcher script, or will it harm the installation on non-SElinux systems?

**Comment by freeplant** [comment]
Please try the latest version. `launcher` is no longer used.
