### ISSUE TITLE
Attempting to start docker image 6.3.3 on Centos 7.5, having exactly the same output as issue #2058

### ISSUE THREAD

**Issue by pz76home** [haiwen/seafile-docker#114]
I did have selinux set on permissive mode, though still have same issue with it disabled.
Also would probably prefer that there is a future release where you can have a separate database container. As I find this works quite well for wordpress and using docker-compose to have them linked together.

**Comment by shoeper** [comment]
https://github.com/haiwen/seafile/issues/2058

**Comment by shoeper** [comment]
It is unlikely that this is a bug. Use the [forum](https://forum.seafile.com/) for questions, please.

At least there is no information given. The linked issue was due to an old broken image.

**Comment by pz76home** [comment]
shoeper,

Quoting haiwen/seafile#2058, there post was not phrashed as a question either?

In my experience this is one of the worst put together docker images I have come across.

**Comment by shoeper** [comment]
> Quoting haiwen/seafile#2058, there post was not phrashed as a question either?

The phrasing is not important, the content is. And your, as well as the other post is just a call for help, not an issue where a specific problem is being reported including further information.

> In my experience this is one of the worst put together docker images I have come across.

I do not deny that.

**Comment by pz76home** [comment]
Ok, I owe you guys an apology.

The issue was with the docker storage driver and disk layout of the AWS centos image I am using. (Uses non lvm xfs root partition" 

I had to change the storage type from overlay2 to devicemapper in /etc/syssysconfig/docker-storage

DOCKER_STORAGE_OPTIONS="--storage-driver devicemapper "
