### ISSUE TITLE
Wrong Share Link

### ISSUE THREAD

**Issue by darkdragon-001** [haiwen/seafile-docker#115]
When I create a share link within "Cloud File Browser" from Seafile Client (Ubuntu), I receive the IP instead of the hostname and port `8000` instead of port `80`.

**Comment by shoeper** [comment]
It is unlikely that this is a bug. Use the [forum](https://forum.seafile.com/) for questions, please.

SERVICE_URL is wrong.

**Comment by darkdragon-001** [comment]
Thanks for the hint. I fixed it by changing `seafile/conf/ccnet.conf`. Anyway, I think that environment variables (specifically `SEAFILE_SERVER_HOSTNAME`) should take precedence in a docker environment!

**Comment by darkdragon-001** [comment]
@shoeper Stumbled over this error again. Is there any plan to read environment variables for this?

**Comment by shoeper** [comment]
I'm sorry. As of now I agree that this is a misconfiguration. The docker image should work upon start but does not due to misconfigured SERVICE_URL

**Comment by darkdragon-001** [comment]
I recommend redesigning the startup scripts and improving environment variable parsing ([e.g. ports](https://github.com/haiwen/seafile-docker/issues/134)) for better configuration via `docker-compose.yml`.

**Comment by ghostry** [comment]
不明白官方什么意思,不允许用户换端口.
从2017年到现在,这个问题仍然没有解决,7.0.5仍然提示
```
Forbidden (403)
CSRF verification failed. Request aborted.

More information is available with DEBUG=True.
```
