### ISSUE TITLE
migration + upgrade issues - start docker without starting seafile server

### ISSUE THREAD

**Issue by joukhaha** [haiwen/seafile-docker#12]
I'm struggling to migrate from an old non-docker seafile install to a docker install, and at present it seems I will need a way to enter the seafile container without immediately launching the seafile servers to be able to update mysql databases and to run the update scripts of seafile data. If the seafile services are stopped from within the container, the container exits due to a watchdog iincluded in scripts/start.py

Since this turned out to be a bit of a challenge I thought to document the need and the key points of the process here. Upon starting the seafile container it executes scripts/start.py so I decided to include a mechanism to interrupt the normal startup procedure before starting the seafile services. At present I simply do this by adding to start.py a snippet 

    controller_pid = get_command_output('ls /shared/seafile-block-pid || true').strip()
    if not controller_pid:
        print 'Starting normally'
    else:
        print 'dont start, exit after sleep period'
        time.sleep(10000000);
        sys.exit(1)

just after the wait_for_mysql() command. (note that this probably requires also disabling the check for consistent git-image in ./launcher - see the issue " installation process does not work for SELinux enabled host #11" )

This prevents seafile services from starting if the file shared/seafile-block-pid exists. Then the normal launcher enter command can be used to work in the container without seafile. Removing/renaming the file then enables the normal startup process.

Is there a better/less ugly way to enter the container/migrate a setup from an old server to seafile? I also stumbled upon the ability to mount existing containers to a new temporary container using docker run --volumes-from CONTAINER -v container_path :mountpoint, but I wasn't able to figure out if this would be useful or not.

**Comment by joukhaha** [comment]
Turned out that docker image already knew the necessary update processes but the overall process upgrading from 4.0.6 to 6.0.7 had a lot of issues caused primarily because the upgrade scripts not being able to locate seahub_settings.py anywhere and the somewhat unexisting instructions to copy data and databases to shared-folder.

To migrate succesfully it was then necessary to copy the old seafile installation to shared/seafile/ and the old mysql database to shared/db before running launcher bootstrap and friends. To solve the missing seahub_settings.py problem I modified the upgrade script as below prior to starting the container (probably more aesthetic solutions also exist but I wasnt' able to figure out a way to copy the file to the container without running the container and I also wasn't willing to modify the paths). Obviously this was not a neat solution but it solved the problem for me. If this is a recurring problem also for others it'd be best to modify the search paths for seahub_settings.py in the upgrade script.

--- /tmp/seafile/scripts/upgrade.py	2017-02-22 08:57:09.157596924 +0200
+++ /var/seafile/scripts/upgrade.py	2017-02-22 09:40:58.042142088 +0200
@@ -73,6 +73,10 @@
 def main():
 wait_for_mysql()
 
+    shutil.copyfile('/shared/seahub_settings.py', installdir+'/seahub_settings.py')
+    shutil.copyfile('/shared/seahub_settings.py', '/opt/seafile/seahub_settings.py')
+    #time.sleep(10000)
+
 os.chdir(installdir)
 check_upgrade()

**Comment by simonsan** [comment]
I'm working at a migration from a normal seafile installation to a docker container. Can anyone help there, started a new page in the wiki. Struggling myself, as the docker container won't start up properly.

https://github.com/haiwen/seafile-docker/wiki/HowTo:-Migrate-from-a-normal-Seafile-installation-to-a-docker-container

Thank you

**Comment by freeplant** [comment]
Please try the latest version. `launcher` is no longer used.
