### ISSUE TITLE
Update Documentation for Docker Pull

### ISSUE THREAD

**Issue by edmenendez** [haiwen/seafile-docker#123]
Currently, in Windows README it states this you should pull the 6.2.1 version. However, it should state a newer version since 6.2.1 is not available. https://github.com/haiwen/seafile-docker/blob/master/README.windows.md

PS C:\seafile> docker pull seafileltd/seafile:6.2.1
Error response from daemon: manifest for seafileltd/seafile:6.2.1 not found

This seemed to work:
PS C:\seafile> docker pull seafileltd/seafile:6.2.5

**Comment by shoeper** [comment]
Just get the most recent tag from https://hub.docker.com/r/seafileltd/seafile/tags/
