### ISSUE TITLE
Allow configuration of ports 80 and 443 rather than hard coding

### ISSUE THREAD

**Issue by mdovey** [haiwen/seafile-docker#134]
The docker image is hard coded to use port 80 for http, and port 443 for https.

In some circumstances it may be preferable to use different ports. However, using (for instance) -p 8443:443 to try to map a different external port to route to the docker image port will trigger CSRF errors.

It would be better to allow these ports to be configured on the docker command line for example

-e SEAFILE_SERVER_HTTP_PORT=8080
-e SEAFILE_SERVER_HTTPS_PORT=8443

**Comment by mayel** [comment]
+100 
This has preventing me from getting up and running with Seafile today, as I want to host it on a sever that is already hosting other things on 443. Thanks

**Comment by lilarcor** [comment]
that will be awesome, 80 and 443 are forbidden in some regions.

**Comment by freeplant** [comment]
This feature will add extra support effort to us. It also add complex to Let'Encrypt CA renew. So it will not be added.

**Comment by lilarcor** [comment]
very sad to hear about it

**Comment by jmooo** [comment]
Not even considered for a potential feature improvement, just ticket closed? Being able to configure the ports an application runs on is pretty fundamental

**Comment by whalehub** [comment]
@freeplant Are you seriously expecting users to dedicate an entire virtual machine just to Seafile? This is ridiculous. I have over 50 Docker containers running on my VM and every single one of them allows you to configure the port. Seafile is the one exception.

**Comment by lilarcor** [comment]
@whalehub you have my vote!!!
