### ISSUE TITLE
is the docker image version synced with github's

### ISSUE THREAD

**Issue by lilarcor** [haiwen/seafile-docker#137]
seems the image on docker.com is little older than the released version here

**Comment by freeplant** [comment]
The latest community edition is 6.3.3. The image on docker.com is already the latest one.

**Comment by lilarcor** [comment]
thanks, I saw 6.3.9 is the latest version. Now I can see it's pro edition. Thanks. Hope the new version will come to commu as well, as I experienced the custom port issue.
