### ISSUE TITLE
Version 6.0.9

### ISSUE THREAD

**Issue by morph027** [haiwen/seafile-docker#14]
> ## About
> Docker makes it much easier to deploy a Seafile server on your servers and keep it updated.

How can we get version 6.0.9? ;)

**Comment by shoeper** [comment]
Please ask questions in the forum. https://forum.seafile.com

**Comment by ks1962** [comment]
+1

**Comment by ks1962** [comment]
I would like to get 6.0.9 too and I posted the question in the seafile forum - no answer until now

**Comment by libeanim** [comment]
Everything is updated now: 5f89412d04f380c05a8e12394628ac3522ae7bed :+1: 
This issue can be closed :white_check_mark:

**Comment by morph027** [comment]
Thank you!
