### ISSUE TITLE
设置容器环境（用户名密码）没用

### ISSUE THREAD

**Issue by wangyanwen** [haiwen/seafile-docker#147]
系统debian9，按docker官方文档安装的docker ce。
按readme说明在容器启动时设置了用户名密码，但没用，还是只能用缺省用户me登录，用reset-admin.sh脚本可以新增。

**Comment by renfeipeng** [comment]
我在centos 7 下测试了最新的seafile-docker镜像，并未发现有任何这方面的问题。方便发一下你启动容器时的命令吗，注意这个环境变量只有在第一次运行容器并且没有使用旧的seafile数据 时才生效的。

**Comment by wangyanwen** [comment]
docker run -d --name seafile -e SEAFILE_SERVER_HOSTNAME=seafile.***** -e SEAFILE_ADMIN_EMAIL=*******@qq.com -e SEAFILE_ADMIN_PASSWORD=******* -v /opt/seafile-data:/shared -p 80:80  seafileltd/seafile:latest

**Comment by wangyanwen** [comment]
另外有个问题，用手机端产生共享链接时，链接端口号是8000，但实际上应该是80，因为容器在主机上只打开了80端口。
这是容器上打开的端口：
root@0d76ed6c3b61:/opt/seafile# netstat -nlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:8000            0.0.0.0:*               LISTEN      174/python2.7       
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:11211           0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      46/nginx: master pr 
tcp        0      0 0.0.0.0:8082            0.0.0.0:*               LISTEN      141/seaf-server     
tcp6       0      0 :::11211                :::*                    LISTEN      -                   
这是主机上打开的端口
wyw@linode:~$ netstat -nlp
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      -                   
tcp6       0      0 :::80                   :::*                    LISTEN      -                   
tcp6       0      0 :::22                   :::*                    LISTEN      -                   
tcp6       0      0 :::4000                 :::*                    LISTEN      12170/hexo          
udp        0      0 0.0.0.0:38142           0.0.0.0:*                           -                   
udp        0      0 0.0.0.0:443             0.0.0.0:*                           -

**Comment by freeplant** [comment]
你需要设置正确的 SERVICE_URL
