### ISSUE TITLE
Publish Docker Container under Different Port

### ISSUE THREAD

**Issue by libeanim** [haiwen/seafile-docker#15]
Hi guys,

I want to deploy the seafile-server under a different port (e.g. 8200).

**What I did**
1. Setting the hostname + port mapping in the `bootstrap/bootstrap.conf` to:
   ```
   server.hostname = <local ip>:8200
   server.port_mappings = 8200:80
   ```
   (where `<local ip>` represents the lan ip address of the server containing the docker container, e.g. 192.178.1.2)

2. Build the image: `./launcher bootstrap`
3. Set `SERVICE_URL` to `http://<local ip>:8200` and the `FILE_SERVER_ROOT`to `http://<local ip>:8200/seafhttp` via the `ccnet.conf` and `seahub_settings.py`
4. Start the container: `./launcher start`

**The proplem**  
When I want to connect, I get redirected to the wrong address. In this case `http://<local ip>/accounts/login?next=/` instead of `http://<local ip>`**`:8200`**`/accounts/login?next=/`

**Did I miss something or is there a bug?**

**Comment by libeanim** [comment]
The redirects are caused by nginx, one solution would be to change the following line in the `seafile.nginx.conf`:
```
proxy_set_header Host       $host;
```
to
```
proxy_set_header Host       $host:8200;
```
More info: http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_set_header

However there are probably other changes required in order to ger letsencrypt working.

**Comment by myme5261314** [comment]
Why closing this issue, it still remains.

**Comment by myme5261314** [comment]
Ok, I figure out that following your instruction (notice to modify the seafile.nginx.conf at /etc/nginx/sites-enabled/ in **docker** container) will make it ok to deploy the seafile on another port other than 80.
Seems need to improve the scripts to let seafile support that more formally. @haiwen

**Comment by libeanim** [comment]
The easiest solution would be to change the `Host` parameter to:

```
proxy_set_header Host $http_host;
```

In this case one can publish the container under any port, without nginx redirecting to port 80 or 443.
E.g.:
```
# for http
server.port_mappings = XXXX:80
# for https:
Server.port_mappings = XXXX:443
```
Where `XXXX` is your desired port. 

It is also not required to set the port in the `server.hostname`. It is important to mention that letsencrypt will not work because it requires port 80 to be accessible. 

The down side (see link in previous post) is: 'However, if this field [$http_host] is not present in a client request header then nothing will be passed.'
Which is probably not a big problem.

**Comment by ElectroDr3am** [comment]
Can anybody share working example of how to change default port at least for http? I'm trying to repeat needed steps but it doesn't work like I'm missing something or make too much config changes. Thanks.

**Comment by freeplant** [comment]
Please try the latest version. `launcher` is no longer used.

**Comment by Jip-Hop** [comment]
Can this issue be reopened? I still experience this behaviour (redirecting to port 80) on the latest Seafile Pro Docker image.

**Comment by fcying** [comment]
Test pass in latest seafile-pro, thanks libeanim.


modify file `/etc/nginx/sites-enabled/seafile.conf`
```
proxy_set_header Host $http_host;
```
service nginx restart

run seafile-pro with `-p PORT:80`
