### ISSUE TITLE
Unable to write 'random state' e is 65537 (0x10001) during bootstrap

### ISSUE THREAD

**Issue by simonsan** [haiwen/seafile-docker#16]
Generating RSA private key, 4096 bit long modulus
.++
..................................................................................++
unable to write 'random state'
e is 65537 (0x10001)
Generating RSA private key, 4096 bit long modulus
..........................................................++
.......++
unable to write 'random state'
e is 65537 (0x10001)

Could it be, that the key generated by the bootstrapping process could not get random numbers, so the cert and key are not secure?

**Comment by kmoe** [comment]
Getting the same error (on `4.11.2-1-ARCH`).

**Comment by freeplant** [comment]
Please try the latest version. `launcher` is no longer used.
