### ISSUE TITLE
Seafile Container error

### ISSUE THREAD

**Issue by hakervip** [haiwen/seafile-docker#163]
Hello, I have a problem with running latest Seafile 7.0.3 docker image. 
I used docker-compose.yml from official Seafile deployment documentation 
[Deploy Documentation](https://download.seafile.com/published/support/docker/deploy%20seafile%20with%20docker.md)

When I set TIME_ZONE env default 'Etc/UTC' or any other timezone like 'Europe/Warsaw' container crushed with following error:
`*** Running /etc/my_init.d/01_create_data_links.sh...,
invalid time zone,
*** /etc/my_init.d/01_create_data_links.sh failed with status 1,
,
*** Killing all processes...,`

I found that when I commented TIME_ZONE env in docker-compose.yml the container start without problem.

After ssh into container I found that there is no /usr/share/zoneinfo folder, so I add 
`- /usr/share/zoneinfo:/usr/share/zoneinfo:ro`
into docker-compose.yml volumes: section.

After that TIME_ZONE env works as expected. I tried that on fresh Debian 9, Debian 10, and Ubuntu 18.04 and I have that error on all system. 

Can you confirm that error?

**Comment by jonasbardino** [comment]
Same here: seafile container aborts right away with 'invalid time zone' error if TIME_ZONE is set at all in docker-compose.yml. Adding a working /usr/share/zoneinfo directory e.g. with the mentioned volume rule solves the problem.

**Comment by renfeipeng** [comment]
We have fixed this bug.
