### ISSUE TITLE
Use $proxy_add_x_forwarded_for in nginx template for X-Forwarded-For header

### ISSUE THREAD

**Issue by icpz** [haiwen/seafile-docker#167]
Hello, I'm in situation to put docker services behind a custom nginx frontend.
This frontend will set the correct `X-Forwarded-For` header, but it's override by the nginx inside the docker image [here](https://github.com/haiwen/seafile-docker/blob/d2a57818dbcf10557eb118897c7976794637dcb9/templates/seafile.nginx.conf.template#L38).

Could you please replace that line with:
```
    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
```

This will prevent the existing `X-Forwarded-For` from being changed, and set it to $remote_addr if not exist.

**Comment by renfeipeng** [comment]
Thank you for your suggestion, we will improve this configuration on the next release.

**Comment by Redsandro** [comment]
I think it would make sense to replace all X-Forwarded headers:

```diff
-        proxy_set_header Forwarded "for=$remote_addr;proto=$scheme";
+        proxy_set_header Forwarded "for=$proxy_add_x_forwarded_for;proto=$http_x_forwarded_proto";
-        proxy_set_header X-Forwarded-For $remote_addr;
+        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
-        proxy_set_header X-Forwarded-Proto $scheme;
+        proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
-        proxy_set_header X-Real-IP $remote_addr;
+        proxy_set_header X-Real-IP $proxy_add_x_forwarded_for;
```

See https://github.com/haiwen/seafile-docker/issues/91#issuecomment-524914187

**Comment by Balooforever** [comment]
Thank @Redsandro, it's work but i get insecure for picture, same for you ?
