### ISSUE TITLE
Add a flag to use existing MySQL installation

### ISSUE THREAD

**Issue by simonsan** [haiwen/seafile-docker#17]
Hey there,
it would be nice to have a flag during install to use a MySQL installation outside of the container. Right now you have to exec

    service mysql stop

inside the container to have a portmapping for 3306.

I'm migrating myself to a docker container right now, so maybe I will post a code snippet for the launcher-file myself in the next days/weeks.

**Comment by tholu** [comment]
#102 will solve this.

**Comment by freeplant** [comment]
Since 7.0, Seafile docker uses multiple containers. You can use an existing MySQL container now.
