### ISSUE TITLE
Wrong timezone ( TIME_ZONE ENV )

### ISSUE THREAD

**Issue by lukasmrtvy** [haiwen/seafile-docker#170]
I am trying to run seafile-mc image with `-e TIME_ZONE=Europe/Prague` -> complains about invalid time zone.
Ty

**Comment by JeanLouPtflbx** [comment]
same thing here with TIME_ZONE=Europe/Paris

seafile      | *** Running /etc/my_init.d/01_create_data_links.sh...
seafile      | invalid time zone
seafile      | *** /etc/my_init.d/01_create_data_links.sh failed with status 1
seafile      |
seafile      | *** Killing all processes...
seafile exited with code 1

**Comment by MJPA** [comment]
You can't specify one, the script that checks the timezone is broken.

It checks for the timezone in `/usr/share/zoneinfo/` but that directory does not exist.

**Comment by renfeipeng** [comment]
This was a bug before, but we have fixed it recently.
