### ISSUE TITLE
Backup Database fails after upgrade to 7.0.4

### ISSUE THREAD

**Issue by bhendrik** [haiwen/seafile-docker#174]
After upgrade from version 6 to 7.0.4 when I try to run the backup commands:

`docker exec -t seafile-mysql mysqldump  -uroot --opt ccnet_db > ccnet_db.sql`

I get the following error:

`mysqldump: Got error: 1524: "Plugin 'unix_socket' is not loaded" when trying to connect`

By adding: 
`plugin-load-add = auth_socket.so` 
to /etc/mysql/conf.d/mariadb.cnf, error stops, but returns as soon as seafile is restarted.
Any way to make this permanent?

**Comment by renfeipeng** [comment]
You can try:
`docker exec -t seafile-mysql mysqldump -uroot -h127.0.0.1 --opt ccnet_db > ccnet_db.sql`
or:
 `docker exec some-mariadb sh -c 'exec mysqldump --all-databases -uroot -p"$MYSQL_ROOT_PASSWORD"' > /some/path/on/your/host/all-databases.sql`

**Comment by bhendrik** [comment]
First line worked when adding in the password for the root mysql user.
`docker` exec -t seafile-mysql mysqldump -uroot -p"$MYSQL_ROOT_PASSWORD" -h127.0.0.1 --opt ccnet_db > ccnet_db.sql`

Thanks for your help
