### ISSUE TITLE
README.md: link to Update Documentation broken

### ISSUE THREAD

**Issue by christophberger** [haiwen/seafile-docker#178]
The link "Upgrade Documentation" in README.md, section "For Seafile 7.x.x" points to a non-existing page. 

I found the "6.3 upgrade to 7.0" document at: `https://download.seafile.com/published/seafile-manual/docker/6.3%20upgrade%20to%207.0.md`

Current link is: `https://download.seafile.com/published/support/docker/6.3%20upgrade%20to%207.0.md`

**Comment by renfeipeng** [comment]
Thank you for your reminder. I will update the README.
