### ISSUE TITLE
use custom ssl cert , how to skip verifying

### ISSUE THREAD

**Issue by lilarcor** [haiwen/seafile-docker#185]
as I don't have 443 port open, so if I use SEAFILE_SERVER_LETSENCRYPT=true and custom ssl vert, the container will verify the ssl and got error
`
ValueError: Wrote file to /var/www/challenges/OeGDXNi7lBSh8vx_gyVMJRp6ZLmL92PcvI8n1P26L0k, but couldn't download http://seafile.xxx.com/.well-known/acme-challenge/OeGDXNi7lBSh8vx_gyVMJRasd123PcvI8n1P26L0k: Error:`

**Comment by renfeipeng** [comment]
I guess you should not follow the instructions in the manual to pre-populate the custom certificate file, otherwise it will automatically skip this problem.
```
If you want to use your own SSL certificate and the volume directory of Seafile data is /opt/seafile-data:
create a folder /opt/seafile-data/ssl, and put your certificate and private key under the ssl directory.
Assume your site name is seafile.example.com, then your certificate must have the name seafile.example.com.crt, and the private key must have the name seafile.example.com.key.
```
