### ISSUE TITLE
How to run seaf-fuse with the docker container server

### ISSUE THREAD

**Issue by mbeynon** [haiwen/seafile-docker#19]
I'm interested in fuse access to the seafile file data outside the container so I can use read-only command line tools to copy uploaded files around as needed for our sysadmin workflow.  Is support for seaf-fuse planned in seafile-docker?

I can see this work one of two ways --

1. run seaf-fuse inside the seafile docker container, passing `--privileged --cap-add=SYS_ADMIN --device /dev/fuse` when started, and mapping the fuse mountpoint out of the container for read-only access.

2. run seaf-fuse outside the container by accessing the `shared/db/...` data to create the view at the fuse mountpoint.  Is this even possible or does seaf-fuse interact directly with the seafile process?

Thank you.

**Comment by satheras** [comment]
I tried the first possibility! At least it is possible to get seafile and fuse WITHIN the Container running...

1. install fuse on the baremetal os

2. create the mountpoint and make sure it is also somehow integrated with the docker columes

3. run the container with those options:
  --cap-add SYS_ADMIN \
  --device /dev/fuse \
  --security-opt apparmor:unconfined \
3. start docker fuse
Now you should be able to start it from within the container...

But if you try to access it from the underlying baremetal operating system you just see an empty folder

Anybody did this already?! Any suggestions how i can get the fuse-folder exposed?

thanks in advance

**Comment by martinplattnr** [comment]
+1
Would also like to know how to use seaf-fuse when running seafile using docker.

**Comment by lilarcor** [comment]
I don't think the official docker has fuse installed, hope next version can include this part

**Comment by schnawel007** [comment]
@satheras If I use a own folder for fuse (outside the shared folder) and mount it separately with this [method](https://stackoverflow.com/questions/43687025/s3-mounted-inside-the-container-how-to-expose-it-to-the-host) I got it running.

**Comment by createchange** [comment]
@schnawel007 Can you provide your docker run parameters so I can see how you got that set up?

Thanks!

**Comment by createchange** [comment]
I got it. For posterity, here is my docker run command:

```
docker run -d \
        --name fuse-test-seafile \
        -e SEAFILE_SERVER_HOSTNAME=seafile2.kvm-host.com \
        -e SEAFILE_ADMIN_EMAIL=me@example.com \
        -e SEAFILE_ADMIN_PASSWORD=asecret \
        --network proxy \
        --label traefik.port=80 \
        --label traefik.frontend.rule="Host:seafile2.kvm-host.com" \
        --label traefik.frontend.entryPoints=http \
        --privileged \
        --cap-add SYS_ADMIN \
        --cap-add MKNOD \
        --device /dev/fuse \
        -v /opt/fuse-seafile-test/:/shared \
        -v /home/jonathanweaver/docker/seafile/data/seafile-fuse:/data/seafile:shared \
        seafileltd/seafile:latest
```
After the docker container is created, then you need to get into the container:
`docker exec -it container_name /bin/bash`

```
cd seafile-server-6.3.3/
./seaf-fuse.sh start /location/defined/above
```

Hope this helps someone!

**Comment by brintal** [comment]
@createchange Did you by any chance create a dockerfile incorporating all these options, so manually starting the script is not necessary anymore? If you would publish that to docker hub I'm sure it would be helpful for others (including me :) )

**Comment by CodingCrush** [comment]
> @createchange Did you by any chance create a dockerfile incorporating all these options, so manually starting the script is not necessary anymore? If you would publish that to docker hub I'm sure it would be helpful for others (including me :) )

I implemented it in another way

step1: 
create `fuss/run.sh`

#!/bin/bash
exec 2>&1
cd /opt/seafile/seafile-pro-server-7.0.13/
./seaf-fuse.sh start /data/seafile-fuse

step2: mount it to /etc/service  in docker-compose 
```
    privileged: true
    ports:
      - "80:80"
      - "8082:8082"
    volumes:
      - /srv/documents/seafile-data:/shared  
      - /data/seafile-fuse:/data/seafile-fuse:shared
      - $PWD/fuse:/etc/service/fuse
```

then you will see it in /data/seafile-fuse from the host

**Comment by dokbua** [comment]
I presume you meant "create **fuse**/run.sh" in step 1 ?

When I start fuse, I get this:

```
Starting seaf-fuse, please wait ...
fuse: device not found, try 'modprobe fuse' first
Failed to start seaf-fuse
```

modprobe/insmod is not present in the container. 

Does anyone have a Dockerfile for seafile-mc ?

**Comment by plourenco** [comment]
It would be interesting if there was a configurable option to automatically mount the seafile storage using seafuse when seafile starts. It's quite complicated to manage auto-mounting with docker...

**Comment by MG-Sky** [comment]
> > @createchange Did you by any chance create a dockerfile incorporating all these options, so manually starting the script is not necessary anymore? If you would publish that to docker hub I'm sure it would be helpful for others (including me :) )
> 
> I implemented it in another way
> 
> step1: create `fuss/run.sh`
> 
> #!/bin/bash exec 2>&1 cd /opt/seafile/seafile-pro-server-7.0.13/ ./seaf-fuse.sh start /data/seafile-fuse
> 
> step2: mount it to /etc/service in docker-compose
> 
> ```
>     privileged: true
>     ports:
>       - "80:80"
>       - "8082:8082"
>     volumes:
>       - /srv/documents/seafile-data:/shared  
>       - /data/seafile-fuse:/data/seafile-fuse:shared
>       - $PWD/fuse:/etc/service/fuse
> ```
> 
> then you will see it in /data/seafile-fuse from the host

thanks i have slightly modified the code:


#!/bin/bash
exec 2>&1
cd /opt/seafile/seafile-server-latest/

process=$(pgrep --count  seaf-fuse)

if [ ! -z "$process" -a "$process" == "0" ]; then
        ./seaf-fuse.sh start /seafile-fuse
fi


also filename is run not run.sh
