### ISSUE TITLE
Custom MySQL Port

### ISSUE THREAD

**Issue by tafoya** [haiwen/seafile-docker#191]
Is there an environment variable to specify a custom MySQL port?

**Comment by notSoWiseOldMan** [comment]
From a quick look at the code there doesn't appear to be. I would be interested in this feature as well.

**Comment by notSoWiseOldMan** [comment]
Looks like [it can be set](https://github.com/haiwen/seafile-docker/blob/master/cluster/scripts/setup-seafile-mysql.py#L934) but the startup script [hard codes the port](https://github.com/haiwen/seafile-docker/blob/df2628d4cd4fce711285b70182fe9d1ea49fd09c/scripts/utils/__init__.py#L275) when waiting for the db to come up.

It looks like `env` is just passed to `setup-seafile-mysql.py` [here](https://github.com/haiwen/seafile-docker/blob/master/scripts/bootstrap.py#L145). Would it be as simple as adding `'MYSQL_PORT': get_conf('DB_PORT','3306'),` to `env` and updating the wait function to read from the environment?

**Comment by notSoWiseOldMan** [comment]
Looks like someone even made a PR already: https://github.com/haiwen/seafile-docker/pull/161

**Comment by freeplant** [comment]
It is supported in the latest version: https://manual.seafile.com/docker/deploy_seafile_with_docker/#use-an-existing-mysql-server
