### ISSUE TITLE
Support MySQL without root access

### ISSUE THREAD

**Issue by HansAdema** [haiwen/seafile-docker#194]
I would like to deploy Seafile in Docker in Kubernetes. I can run the application and memcached DB in there, but I already have a separate MySQL database running outside the cluster which I would like to use for Seafile.

The thing is that this database is used by other tools as well, so I would like to setup the database and user for Seafile myself. However, this Docker image will refuse to start without root access to the database.

Ironically, the `setup-seafile-mysql.py` script supports this use case already, but the scripts in the `/scripts` folder has various hard coded references to the root user `DB_ROOT_PASSWD` key.

I would like to see the possibility to pass a custom username, password and database name instead of the root password.

**Comment by GRBurst** [comment]
@lins05 we haven't seen any commits for a while now. #187 also targets this feature. Are there any plans supporting this?

**Comment by renfeipeng** [comment]
Very sorry.
For other reasons, we cannot support this feature in the release image. 
If you need this feature, I suggest that you can build a seafile image on your own to use it.

**Comment by GRBurst** [comment]
> Very sorry.
> For other reasons, we cannot support this feature in the release image.
> If you need this feature, I suggest that you can build a seafile image on your own to use it.

Hey, thanks for the reply @renfeipeng. I think that is totally fine, but could you please tell us what these *other reasons* are? Just being curious :-)

**Comment by HansAdema** [comment]
I'm curious about why this was rejected too. I applaud the fact that Docker support was at least considered, but the current image heavily focuses on the docker-compose based setup, and is quite cumbersome to work with in most other scenarios.

If Docker support isn't a focus for Seafile right now, or a larger revamp to improve the versatility is coming up, that's fine too. But that's why I went through the effort myself to offer a fix.
