### ISSUE TITLE
Docker image for armv7

### ISSUE THREAD

**Issue by chasewinnings391** [haiwen/seafile-docker#206]
Is it possible to obtain a docker file for version 7.0.5 for armv7? 

The following fork is only for 6.3.4 unfortunately
https://github.com/domenukk/seafile-docker-pi

**Comment by lbischof** [comment]
I created an armv7 image for version 7.1.4: https://hub.docker.com/r/lbischof/seafile-armhf 

The Git-repository: https://github.com/lbischof/seafile-armhf

I haven't fully tested it, but it seems to work. You can use the `linuxserver/mariadb` database which is compatible with arm.

**Comment by ChriZ982** [comment]
Indeed, official arm support would be very much appreciated. Maybe even for arm64.
