### ISSUE TITLE
exec format error - ubuntu 19.10 64-bit Raspberry pi 4

### ISSUE THREAD

**Issue by Shlokp** [haiwen/seafile-docker#207]
I am trying to install seafile to my ubuntu 19.10 64bit install on the raspberry pi 4 however the seafile container doesnt start.

I get the following error
`standard_init_linux.go:211: exec user process caused "exec format error"`

I was under the impression this error is because of using a 64bit image on 32bit system but I am using 64bit os.

**Comment by XGTIGER** [comment]
The same with my situation,any idea?

**Comment by t3ste** [comment]
Why is this issue closed?
It is the same for me on 64 bit Ubuntu Server running on a RPi 4.

**docker logs seafile**
`standard_init_linux.go:228: exec user process caused: exec format error`


**Model           : Raspberry Pi 4 Model B Rev 1.4**
**cat /etc/os-release**
```
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
