### ISSUE TITLE
A rebuild doesn't remove the old docker image

### ISSUE THREAD

**Issue by libeanim** [haiwen/seafile-docker#21]
After calling `./launcher rebuild` a new container image is build, however the old image (`local_seafile/server:latest`) doesn't get removed and is now shown as `<none>:<none>`:
```
$ sudo docker images
REPOSITORY             TAG                 IMAGE ID            CREATED             SIZE
local_seafile/server   latest              7960eb51b534        20 seconds ago      824 MB
<none>                 <none>              40f5c8086ec9        21 minutes ago      824 MB
<none>                 <none>              af6c195a6b48        About an hour ago   824 MB
seafileltd/seafile     6.0.7               8654b3e742ad        4 months ago        824 MB

```

**Comment by lins05** [comment]
We can borrow the idea from discourse, i.e. add a "./launcher docker-gc"
command to remove unused containers periodically.

https://github.com/discourse/discourse_docker/blob/aab5d67efdbeb3d79962276ba76e483f90d9679a/launcher#L370-L391

**Comment by libeanim** [comment]
Yeah I see 2 options here:

1. Delete an image before a new one is built:
   ```
   docker rmi $(docker images -q local_seafile/server:latest)
   ```
   (Or temporarily store the image id to remove the image after a successful rebuild)
2. Introduce a launcher command which deletes the previous images. Because the image id's of previous images is not tracked, the launcher could execute:
   ```
   docker rmi $(docker images -qa -f "dangling=true")
   ```
   However this would delete all 'dangling' images not only those generated by the launcher. So an alternative would either be to track the image id's or option 1.

Concerning your link, their [docker-gc](https://github.com/discourse/discourse_docker/blob/master/scripts/docker-gc) script starts a container using the [samsaffron/docker-gc](https://hub.docker.com/r/samsaffron/docker-gc/) image. Wasn't able to find any descriptions what this container does but I would imagine it filters the images for dangling ones and removes them similar to the docker command in option 2?

My favourite would be option 1. After an upgrade the user should not start a container based on an old image anyways. One could introduce a flag e.g. `launcher rebuild --delete-previous-image` (/`launcher rebuild -d`) which then deletes the old image if the build was successful.

**Comment by shoeper** [comment]
Launcher is not being used anymore.
