### ISSUE TITLE
Nginx configuration outdated (seafdav)

### ISSUE THREAD

**Issue by rsmuc** [haiwen/seafile-docker#219]
The configuration for nginx is outdated, so Seafdav is not working.
According the Upgrade-Notes Fastcgi is not supported anymore: 
https://download.seafile.com/published/seafile-manual/upgrade/upgrade_notes_for_7.1.x.md

But the nginx configuration in the docker container still uses fastcgi. After replacing the nginx configuration with the mentioned snipped in the upgrade notes seafdav is working again.

**Comment by kestrelhawk** [comment]
@rsmuc Is there any way I can manually add the solution outlined in your merge request to my SeaFile docker installation? I have a few services that are reliant on WebDav connections which are no longer working since I updated to 7.1. Thank you!

**Comment by rsmuc** [comment]
> @rsmuc Is there any way I can manually add the solution outlined in your merge request to my SeaFile docker installation? I have a few services that are reliant on WebDav connections which are no longer working since I updated to 7.1. Thank you!

you can just modify the configuration file in the container

**Comment by sagebind** [comment]
I put the modified file on my file system and then used a volume mount to override the file used in the container.

**Comment by kestrelhawk** [comment]
Worked great, thanks @rsmuc and @sagebind!
