### ISSUE TITLE
Support non-root use

### ISSUE THREAD

**Issue by fuzzykiller** [haiwen/seafile-docker#22]
On my server, I set up my user account to be able to control Docker. I also run Discourse, which works perfectly fine like that.

However, at least the `bootstrap` command currently runs into an error when a container already exists:

    fuzzy@server:/opt/seafile $ ./launcher bootstrap
    touch: cannot touch '/opt/seafile/shared/logs/var-log/syslog': Permission denied

There may be other instances where the launcher tries to access container files that would be owned by UID 0.

My suggestion: Either go through `docker run` to deal with those files or evaluate if accessing them is really necessary. `touch`ing the syslog doesn’t appear all that important to me. :smile:

/edit: Starting also does not work:

    fuzzy@server /opt/seafile $ ./launcher start
    cat: /opt/seafile/shared/seafile/seafile-data/current_version: Permission denied

**Comment by peetipablo** [comment]
Seconded.  Is there a reason this container needs to be launched as the root user?  Isn't this a security concern?

**Comment by freeplant** [comment]
Please try the latest version. `launcher` is no longer used.

**Comment by alexw1982** [comment]
Raising this issue again. It would be great if you define UID/GID of the user running seafile in the container. as it is today all files have to be owned by root (incl. seafile-data) in order to run the docker container.
