### ISSUE TITLE
Cannot proceed to basic installation following readme

### ISSUE THREAD

**Issue by PDS42** [haiwen/seafile-docker#23]
Hello, 

I've done exactly what the README says, and the following error comes up. 

https://gyazo.com/1fcb52a2f998fac5799bc4b470cfcb47

I do not know how to work around this; how do I fix this? Any ideas/solutions welcome :)

**Comment by shoeper** [comment]
It looks like some kind of permission problem.

I just tried it on a fresh Debian 9 and it worked immediately. Took 7 mins including docker installation.

**Comment by PDS42** [comment]
I'm running this on macOS, could this be the problem? Is this supposed to exclusively run on linux ?

**Comment by stevesbrain** [comment]
@PDS42 as a rule of thumb docker will run on Mac. However, these scripts *may* be doing something Linux-specific. Just out of curiosity do you get the same permissions error when running `su`, rather than `sudo`?

**Comment by lins05** [comment]
Right, it's only supposed to run on linux. MacOS is not supported.
