### ISSUE TITLE
[FR] create seafile-only image

### ISSUE THREAD

**Issue by laur89** [haiwen/seafile-docker#232]
Would it be possible to have a [seafile image](https://github.com/haiwen/seafile-docker/blob/master/image/seafile_7.1/Dockerfile) that contains only seafile resource.
Could be used if user already has externally deployed instance of nginx/db/onlyoffice etc.

**Comment by freeplant** [comment]
Nginx is part of Seafile, so it can't be removed. db/onlyoffice are external services that you can run using an existing one. Just modify the docker-compose.yml.
