### ISSUE TITLE
Not ollowed to connect to database

### ISSUE THREAD

**Issue by pide2000** [haiwen/seafile-docker#234]
I've started seafile docker using docker-compose

log says:
`waiting for mysql server to be ready: %s (1130, "Host '172.20.0.4' is not allowed to connect to this MariaDB server")`

My docker-compose file looks like this:
`version: '2.0'
services:
  db:
    image: mariadb:10.1
    container_name: seafile-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password  # Requested, set the root's password of MySQL service.
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - /opt/seafile-mysql/db:/var/lib/mysql  # Requested, specifies the path to MySQL data persistent store.
    networks:
      - seafile-net

  memcached:
    image: memcached:1.5.6
    container_name: seafile-memcached
    entrypoint: memcached -m 256
    networks:
      - seafile-net

  seafile:
    image: seafileltd/seafile-mc:latest
    container_name: seafile
    ports:
      - "127.0.0.1:9080:80"
      #- "443:443"  # If https is enabled, cancel the comment.
    volumes:
      - /opt/seafile-data:/shared   # Requested, specifies the path to Seafile data persistent store.
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=password  # Requested, the value shuold be root's password of MySQL service.
      - TIME_ZONE=Etc/UTC  # Optional, default is UTC. Should be uncomment and set to your local time zone.
      - SEAFILE_ADMIN_EMAIL=me@example.com # Specifies Seafile admin user, default is 'me@example.com'.
      - SEAFILE_ADMIN_PASSWORD=adminpwd     # Specifies Seafile admin password, default is 'asecret'.
      - SEAFILE_SERVER_LETSENCRYPT=false   # Whether to use https or not.
      - SEAFILE_SERVER_HOSTNAME=seafile.my.domain # Specifies your host name if https is enabled.
    depends_on:
      - db
      - memcached
    networks:
      - seafile-net

networks:
  seafile-net:`

**Comment by biozz** [comment]
I had similar issue and didn't quite understand what happened, but managed to find a workaround. Not sure if this is going to work for you though.

I removed seafile user with `DROP USER 'seafile'@'%.%.%.%'`, made sure that there were no other user named `seafile` in db and started again. And it was successful.

My guess is that you might have accidentally changed the password or maybe db data folder was not clean.

As a side note: you can format blocks of code with triple backticks, instead of one.

**Comment by funkyfuture** [comment]
yes, the bootstrapping or whatever is fucking up the database's grant tables. what it did to solve this was adding a file `/docker-entrypoint-initdb.d/seafile.sql` to the db container:

```sql
GRANT ALL ON *.* TO 'root'@'%';
FLUSH PRIVILEGES;
```

mind that this is only applied when no database exists yet.
