### ISSUE TITLE
Enabling fuse in seafile.mc

### ISSUE THREAD

**Issue by dokbua** [haiwen/seafile-docker#235]
Does anyone know how to get fuse working with seafile.mc.  I can enter the container and start the fuse by running 

`/opt/seafile/seafile-server-7.1.5/seaf-fuse.sh start /data/seafile-fuse
`
This creates the /data/seafile-fuse folder with a user folder under it, containing a folder with the same name as a testfile uploaded, but no files are present.

Also, it would be nice to have the Dockerfile for seafile.mc.

**Comment by freeplant** [comment]
You can find the document here: https://manual.seafile.com/extension/fuse/#how-to-start-seaf-fuse-in-docker
