### ISSUE TITLE
Current docker container not working

### ISSUE THREAD

**Issue by Petemir** [haiwen/seafile-docker#261]
Currently there are some issues with the [docker installation option](https://manual.seafile.com/docker/deploy_seafile_with_docker/). The initial mysql scripts fail so the app never starts working. There are several reports about this on the forum:
* [Seafile docker dead on deployment](https://forum.seafile.com/t/seafile-docker-dead-on-deployment/14970/6)
* [Fresh installation on Debian 11 + Docker >> Error from setup-seafile-mysql.py (see latest post)](https://forum.seafile.com/t/fresh-installation-on-debian-11-docker-error-from-setup-seafile-mysql-py-see-latest-post/14962/5)
* [Docker SQL issues?](https://forum.seafile.com/t/docker-sql-issues/14965/1)

**Comment by shanebrowncs** [comment]
Not a solution but downgrading the seafile container to 8.0.6 at least lets it run. Guess they just didn't test this release, fun.

**Comment by Petemir** [comment]
I just want to state that the versions that are not working are 8.0.7 and 8.0.8.

**Comment by williamdlees** [comment]
Thanks for this very helpful message, was tearing my hair out.

**Comment by poperigby** [comment]
Any updates on this?
