### ISSUE TITLE
Weekly cronjob /scripts/fsck.sh Kills Container

### ISSUE THREAD

**Issue by metti-himself** [haiwen/seafile-docker#270]
Hello,

I think there might be a problem with the watch_controller(): in /scripts/start.py, if we run a fsck that seems to run a bit too long.

```python
def watch_controller():
    maxretry = 4
    retry = 0
    while retry < maxretry:
        controller_pid = get_command_output('ps aux | grep seafile-controller | grep -v grep || true').strip()
        garbage_collector_pid = get_command_output('ps aux | grep /scripts/gc.sh | grep -v grep || true').strip()
        if not controller_pid and not garbage_collector_pid:
            retry += 1
        else:
            retry = 0
        time.sleep(5)
    print('seafile controller exited unexpectedly.')
    sys.exit(1)
```

I tried to add an additional check with fsck.sh but got no luck

```python

fsck_pid = get_command_output('ps aux | grep /scripts/fsck.sh | grep -v grep || true').strip()
        if not controller_pid and not garbage_collector_pid and not fsck_pid:
```
After a few seconds I only see seafile controller exited and the container dies. Can anybody give me an hint how to fix this?

Regards

Matthias

**Comment by freeplant** [comment]
When you run fsck, you don't need to story Seafile server (the controller). So you don't need to modify watch_controller().

**Comment by metti-himself** [comment]
Ok thanks for the response @freeplant, should have looked it up in the manual.
