### ISSUE TITLE
Moving from phusion/baseimage to s6-overlay for process supervision

### ISSUE THREAD

**Issue by fakuivan** [haiwen/seafile-docker#286]
Seeing that this scheme of an "all in one container" is here to stay, I'd propose using [s6](https://skarnet.org/software/s6/overview.html) as a process supervisor instead of phusion/baseimage. All docker containers from [linuxserver.io](https://www.linuxserver.io/) and many others use [s6-overlay](https://github.com/just-containers/s6-overlay) to manage multiprocess containers. To me the main advantage is that it would allow us to run the seafile server and maybe nginx as a user other than root.

**Comment by freeplant** [comment]
Current we use Ubuntu 22.04 as the base image.
