### ISSUE TITLE
Multisite on a single server

### ISSUE THREAD

**Issue by zodiacg** [haiwen/seafile-docker#29]
I noticed that seafile-docker is based on discourse-docker project. In discourse by setting the nginx in container to listen on a unix socket, I can host multiple sites using nginx in the host machine.

Is it possible for seafile-docker to do the same? I haven't tried to modify the nginx template yet. Are there more modifications needed?

**Comment by shoeper** [comment]
Not sure if it works with sockets but you can map the ports to different ports on the host an run nginx there as a proxy.

**Comment by skuep** [comment]
I want to do exactly what you propose. Has anybody tried this? Following the README i executed
```
docker run -d --name seafile \
  -e SEAFILE_SERVER_HOSTNAME=mydomain.example \
  -v /opt/seafile-data:/shared \
  -p 8181:80 \
  seafileltd/seafile:latest
```
However when accessing the site under mydomain.example:8181 I get redirected to mydomain.example/accounts/login?next=/ which is obviously not running my seafile instance.

Any Ideas? Anything I missed?

**Comment by Vurgus** [comment]
@skuep 
I had the same issue I think this is the result of the configuration in nginx:
`proxy_set_header Host $host;`
after I change this to:
`proxy_set_header Host $http_host;`
the rewrite works correct.
Is it possible to set this option for further releases?

**Comment by skuep** [comment]
Very nice, I assumed something like this. I changed to corresponding line in /etc/nginx/sites-enabled/seafile.nginx.conf and it is working so far.
In this case it would be very nice indeed to include this change into docker image. However I am not sure if this may cause problems in other places?

**Comment by Vurgus** [comment]
I also asked myself that question.
In the nginx documentation ([http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_set_header](url)) they have some examples and discribe how the diffrent configurations works. 
There is also a option `proxy_set_header Host $host:$proxy_port;` I think this should also work -> But I don't test it.

**Comment by shoeper** [comment]
> However when accessing the site under mydomain.example:8181 I get redirected to mydomain.example/accounts/login?next=/ which is obviously not running my seafile instance.
> 
> Any Ideas? Anything I missed?

I recommend running a proxy on the host. That way all instances can run on port 443 (or 80 without TLS). The redirect would also make sense, again.
