### ISSUE TITLE
Some feedback

### ISSUE THREAD

**Issue by riemers** [haiwen/seafile-docker#30]
Lets encrypt doesn't seems to work, after its done it will check for verification on the domain with the "acme" check if the domain is not yet life. (think of moving servers)

The example is called server.conf and the destination in the bootstrap folder is bootstrap.conf, usually you copy files "as is" and otherwise call them bootstrap.conf.example. I just copied the files but then it just creates a server that does not function at all

For above ^ error, you would not see port 80/443 as being exposed to the outside. (i presume why you have a PR with EXPOSE 80 443, since it works if you have it correct)

Running multiple sites on 1 server doesn't work because of the nginx using up the same port, adding virtual domains and placing a nginx config in the data folder would be a nice idea. Perhaps creating a shared/domainname/ folder and having a nginx in /shared/nginx/ with domainname.conf per server might do the trick.

Add the option to create a self signed cert, if only for testing purpose. You might not have proper internet to create the letsencrypt certs too, but once you do, you can always rebuild right?

These are just some points i noticed when trying to get this to run, trying to help out on things, other then that it does what i want. Nice work.

**Comment by freeplant** [comment]
Please try the latest version. `launcher` is no longer used.
