### ISSUE TITLE
How to use Webdav?

### ISSUE THREAD

**Issue by nbedou** [haiwen/seafile-docker#31]
I am trying to enable Webdav access to my Seafile server. How to do that? I tried the sample configurations 1 and 2 from the [Webdav documentation](https://manual.seafile.com/extension/webdav.html) with no success. Thanks

**Comment by AndrewPaglusch** [comment]
I have it working. Here's how my `seafile/conf/seafdav.conf` file looks:

```
[WEBDAV]
enabled = true
port = 8080
fastcgi = true
share_name = /seafdav
```

**Comment by yatesco** [comment]
@nbedou, it is working for me as well, but make sure you try and mount "whatever-your-server-is.com/seafdav" After entering your username and password, you should see your _unencrypted_ libraries.

**Comment by IvanTurgenev** [comment]
so i do docker run -p 8080 etc, then when seafdav.conf is created i stop the container modify seafdav.conf then docker start seafile container try to access seafile normally but it doesnt work, then i stop the container modify enabled = true to false and then it start normally again, whats going on
