### ISSUE TITLE
First launch on Debian 5.10 through Docker - Error to create admin account

### ISSUE THREAD

**Issue by the-lazy-fox** [haiwen/seafile-docker#310]
Hi,

I've launched the container for the very first time on a clean environment running `Linux version 5.10.0-13-amd64 (debian-kernel@lists.debian.org) (gcc-10 (Debian 10.2.1-6) 10.2.1 20210110, GNU ld (GNU Binutils for Debian) 2.35.2) #1 SMP Debian 5.10.106-1 (2022-03-17)`

First of all, it was impossible to connect to the database so I finally find out that a pip package was missing. I've made a PR for that: https://github.com/haiwen/seafile-docker/pull/309
Then it finally started but failed to create the admin account.

I tried to do it manually with the provided script but the result is the same.
![image](https://user-images.githubusercontent.com/35723598/187742244-c9148a6d-2607-4303-a69d-293f9c00549c.png)

Could you please help me to understand what is wrong with the Docker setup?

**docker image inspect seafileltd/seafile-mc:latest**
```
 "Id": "sha256:5f7b633f220b33a4fbebada7c1ec9453491eb8481b7d3ad95a9f29a1bc20a998",
 "RepoTags": ["seafileltd/seafile-mc:latest"],
 "RepoDigests": ["seafileltd/seafile-mc@sha256:9ec684b6acdecff2476a2647993461800f2f47ef380550e8fb02fb849c1c04e2"]
```

**docker --version**
```
Docker version 20.10.14, build a224086
```

Thank you!

**Comment by wawefr** [comment]
Thank @the-lazy-fox  for your job on this subject Fred

**Comment by SkywalkerSpace** [comment]
We need more error logs to troubleshoot problems.
Please add the following contents to the `/opt/seatable/conf/gunicorn.py` configuration file.

```
# Log
accesslog = '/opt/seatable/logs/gunicorn-access.log'
errorlog = '/opt/seatable/logs/gunicorn-error.log'
```

And then execute `seatable.sh`. There will be more detailed errors in the `/opt/seatable/logs/gunicorn-error.log` log file.
