### ISSUE TITLE
`seafile` Docker container has two identical `seahub.sh` scripts

### ISSUE THREAD

**Issue by kirisakow** [haiwen/seafile-docker#318]
a. `seafile` Docker container has two identical `seahub.sh` scripts:

```sh
root@4c206843a5fd:/opt/seafile# ll /opt/seafile/seafile-server-9.0.9/seahub.sh
-rwxr-xr-x 1 root root 8875 Sep 20 04:39 /opt/seafile/seafile-server-9.0.9/seahub.sh*

root@4c206843a5fd:/opt/seafile# ll /opt/seafile/seafile-server-9.0.9/seahub/scripts/seahub.sh
-rwxr-xr-x 1 root root 8875 Sep 20 04:36 /opt/seafile/seafile-server-9.0.9/seahub/scripts/seahub.sh*
```

b. Seafile manual (https://manual.seafile.com) gives no information as to why there are not one `seahub.sh` script but two `seahub.sh` scripts.

**Comment by freeplant** [comment]
`/opt/seafile/seafile-server-9.0.9/seahub/scripts/seahub.sh` is included in the source code.

`/opt/seafile/seafile-server-9.0.9/seahub.sh` is a copied version when building the docker image.
