### ISSUE TITLE
Unable to use another SQL port other than 3306

### ISSUE THREAD

**Issue by piranha771** [haiwen/seafile-docker#336]
The database port is hardcoded to 3306 for example in utils.py wait_for_mysql()

Please introduce a new environment variable like DB_PORT to allow other ports than 3306

**Comment by SkywalkerSpace** [comment]
Thank you for your feedback, we will support custom mysql ports as soon as possible.

**Comment by SkywalkerSpace** [comment]
We have updated the `seafileltd/seafile-mc:latest` image. 
You can configure the custom db port by referring to the manual [Seafile Admin Manual
Seafile Community Installation](https://manual.seafile.com/docker/deploy_seafile_with_docker/#use-an-existing-mysql-server) .
