### ISSUE TITLE
Seafile Pro : can't renew SSL certs

### ISSUE THREAD

**Issue by timconsidine** [haiwen/seafile-docker#337]
Seafile Professional under Docker
Server is running
Incoming connections are failing in local sync client
Tried to renew certs in docker 
`/scripts/ssl.sh /shared/ssl <domain>`
Script runs and seems to get new cert but fails to write it
```
Creating new order...
Order created!
Verifying domain.tld...
Traceback (most recent call last):
  File "/shared/ssl//letsencrypt/acme_tiny.py", line 145, in get_crt
    assert (disable_check or _do_request(wellknown_url)[0] == keyauthorization)
  File "/shared/ssl//letsencrypt/acme_tiny.py", line 46, in _do_request
    raise ValueError("{0}:\nUrl: {1}\nData: {2}\nResponse Code: {3}\nResponse: {4}".format(err_msg, url, data, code, resp_data))
ValueError: Error:
Url: http://domain.tld/.well-known/acme-challenge/bl9gMQOXxdqvN2aETKxvbwAJTEfS1UMdqKPUeM8nkrM
Data: None
Response Code: None
Response: [Errno 104] Connection reset by peer
```
/shared/ssl shows zero length files for `domain.tld.crt`

Seems incoming connections are being rejected
Can ping the server from local box

How can I solve this ?

**Comment by timconsidine** [comment]
No reply ... but for the benefit of others
I created a simple 'empty' website, pointed the domain there, ran certbot to get a certificate,
Copied those files into /opt/seafil-data/ssl with correct names
Then the system booted into life without any further action.
Client now connecting and syncing

So now the question is :
- why doesn't the system auto renew certs "out of the box" as default ?
- if it's not "out of the box" by default, what's the best way to implement this ?
(I'm not logging in every 90 days)

**Comment by freeplant** [comment]
The problem have been fixed and the docker images are re-uploaded.
