### ISSUE TITLE
seafile-pro-mc:7.1.7 image missing

### ISSUE THREAD

**Issue by jonatino** [haiwen/seafile-docker#339]
Hi all, I have a old backup of a seafile server running pro  7.1.7. I'm trying to restore this to access my files but I can't find this image version here https://docker.seadrive.org/harbor/projects/2/repositories/seafile-pro-mc

Does anyone have a backup of this image?

**Comment by SkywalkerSpace** [comment]
We keep the pro version 7.1.7 in another Harbor repository, you can pull the the image by 
`docker pull docker.seafile.top/seafileltd/seafile-pro-mc:7.1.7`
