### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by Fobhep** [haiwen/seafile-docker#34]
Hi there, 
I am trying to start up the Docker image. However it fails with
"cat: /var/seafile/shared/seafile/seafile-data/current_version: No such file or directory"

According to the launcher script the version_stamp_file is supposed to be in the "shared" dir within the docker dir.
However this dir is empty. Any hints what I am missing out here?

**Comment by Fobhep** [comment]
I will close this issue. Using verbose mode I could figure out that it is an issue related to the fact that I tried to deploy on a Raspberry Pi. I was not aware of the fact, that the Docker-base image for this projekt is not suited for ARM.

**Comment by saljut7** [comment]
> I was not aware of the fact, that the Docker-base image for this projekt is not suited for ARM.

Unfortunately... https://forum.seafile.com/t/seafile-server-in-docker-is-ready-for-testing/1291/5
