### ISSUE TITLE
11.0.0 missing arm64 version on Dockerhub

### ISSUE THREAD

**Issue by Oliver-Hanikel** [haiwen/seafile-docker#346]
I just wanted to update my seafile instance from 10.0.1 to 11.0.0, but I got an exec error and noticed the arm64 Version of 11.0.0 is missing on Dockerhub.

Was the arm64 Version just forgotten or isn't it ready yet or won't there be published Docker images for arm64 anymore?

**Comment by freeplant** [comment]
Arm64 version will be uploaded when we release v11 stable version.
