### ISSUE TITLE
Incomplete/misleading parts in manual for Seafile-CE docker deployment

### ISSUE THREAD

**Issue by whowantsmybigdata** [haiwen/seafile-docker#355]
regarding [the official manual](https://manual.seafile.com/docker/deploy_seafile_with_docker/):

1. Isn't the part for setting up seafile-docker with own ssl certs a bit complicated/even unsafe?

I would suggest, mounting the certs from their original position as read-only could be the better way to do. Could also be more safe considering one might not be restrictive enough with permissions for the copied certs in the new location (regarding the manual '/opt/seafile-data/ssl' because that topic is not mentioned at all.

Also the part for how to tell the included nginx in the seafile-container were to look for the certs is missing.

2. There is no part mentioning what to do if some wants to set an individual port for nginx to listen to (because port 443 or 80 are already in use). I know there is a github issue already which is also kind of solved but its not in the manual.

**Comment by SkywalkerSpace** [comment]
Thank you for your feedback.
You can configure volumes in the docker-compose.yml to specify your certs.
```
seafile:
    volumes:
      - /opt/seafile-data:/shared
      - /your-cert-path:shared/ssl/your-cert.crt;
      - /your-key-path:shared/ssl/your-key.key;
```
We will add the custom certs and custom ports to the manual as soon as possible.

**Comment by SkywalkerSpace** [comment]
We have updated the manual.
You can configure the custom certs and custom ports by referring to the manual [Seafile Admin Manual
Seafile Community Installation](https://manual.seafile.com/docker/deploy_seafile_with_docker/#lets-encrypt-ssl-certificate) .
