### ISSUE TITLE
the `download.seafile.com/.../docker-compose.yml` template needs to be upgraded since the `MARIADB_AUTO_UPGRADE` environment variable was introduced

### ISSUE THREAD

**Issue by kirisakow** [haiwen/seafile-docker#367]
The [`docker-compose.yml`](https://download.seafile.com/d/320e8adf90fa43ad8fee/files/?p=/docker/docker-compose.yml) template needs to be upgraded accordingly with https://github.com/haiwen/seafile-docker/issues/358#issuecomment-1867375368:

> About the mariadb-upgrade, we have added `MARIADB_AUTO_UPGRADE=1` in the docker-compose.yml on seafile-manual.

**Comment by SkywalkerSpace** [comment]
Thanks for your feedback.
We have fixed the link to `docker-compose.yml` in the Seafile manual.
