### ISSUE TITLE
upgrade.py - wrong order of updates - includes fix info

### ISSUE THREAD

**Issue by cr1st1p** [haiwen/seafile-docker#37]
I had the surprise to have applied first some 6.* upgrade instead of a 5.0 to 5.1 when data was hosted under NFS (exported from zfs). It worked ok on my local machine.

Reason is that glob() call does not guarantee any order, so you need to do a "sorted(glob....)"
Hope that helps.
Have a nice day!

**Comment by shoeper** [comment]
Having a look at upgrade.py I think the problem still exists. Do you agree?

https://github.com/haiwen/seafile-docker/blob/master/scripts/upgrade.py#L44

**Comment by cr1st1p** [comment]
Agree.

**Comment by zMingGit** [comment]
this will be fixed in the next version.
thanks for reports.

**Comment by shoeper** [comment]
This has been fixed in https://github.com/haiwen/seafile-docker/commit/0e751248e99237cd74816799f5cd0bc206f083a9
