### ISSUE TITLE
Set "X-Frame" Option in header to prevent Clickjacking attacks

### ISSUE THREAD

**Issue by m-terlinde** [haiwen/seafile-docker#384]
Dear team,

in the current deployment of 10.0.1 the X-Frame header option is not set at all.
This reduces the security of the login page.

Is it possible to set the option for the reverse proxy?

Thanks,
Matthias

**Comment by freeplant** [comment]
You can modify the generated Nginx configuration file according to your need after the first run of the docker image.

**Comment by m-terlinde** [comment]
Sure thing, but shouldn't Seafile be in a "secure-by-default" mode?
It would be good to have that for every installation.

**Comment by freeplant** [comment]
Different people have different requirements. For example, some users need to embed a Seafile iframe in their own mobile apps. We don't want to break such use cases.
