### ISSUE TITLE
seafileltd/seafile-mc:latest is not updated

### ISSUE THREAD

**Issue by dominikholler** [haiwen/seafile-docker#399]
`docker://docker.io/seafileltd/seafile-mc:latest` points to `seafileltd/seafile-mc:11.0.9`, but not to `seafileltd/seafile-mc:11.0.12` .  The tag `11.0-latest` is fine.

**Comment by krahl** [comment]
I second this. I set-up Watchtower to do automatic updates and was a bit shocked that I was not running the latest Seafile image. Especially since it contained an important security fix for WebDAV.

> ## [11.0.11 (2024-08-07)](https://manual.seafile.com/changelog/server-changelog/#11011-2024-08-07)
> 
>     [fix] [important] Fix a security bug in WebDAV

**Comment by freeplant** [comment]
We have deleted docker://docker.io/seafileltd/seafile-mc:latest. Please use 11.0-latest instead. Because for each major update, there may be some manually needed steps.
