### ISSUE TITLE
Run on subdomain only

### ISSUE THREAD

**Issue by wdmtech** [haiwen/seafile-docker#4]
Hi, great image! Thanks for taking the time to put this together.

I am using seafile-docker on a server that (will) have multiple sites, for example

`files.mydomain.com` for Seafile
`blog.mydomain.com` for a blog
`mydomain.com` for the main website

Because Nginx seems to be running in the same container as seafile-docker, is it actually possible to support the above configuration? Or is this image designed to only be run on it's own server?

I'm not sure how I can configure multiple docker sites on port 80 as I'd have to configure everything after running `./launcher enter` which doesn't seem ideal.

Any ideas how I could approach this?

Cheers!

**Comment by wdmtech** [comment]
Turns out it was a gap in my knowledge - I ended up setting up nginx on my server and used `proxy_pass` to pass traffic from port 80 to the port I'm using on `seafile-docker` :+1:

**Comment by myme5261314** [comment]
@wdmtech Could you help me with 2 confusion?
1. you might use `proxy_pass` to redirect the `/seafile/*` request on host 80 port to the port you are using, is it ok with the url substitute or rewrite?
2. I can't find any success solution to make seafile-docker to be hosted and visted on host port other than 80, any suggestions? Need to manually modify the generated configuration files?

Thanks
