### ISSUE TITLE
HTTPS Error

### ISSUE THREAD

**Issue by Meerbi** [haiwen/seafile-docker#42]
`[2018-03-14 00:25:25] Generating local Dockerfile ...
[2018-03-14 00:25:25] Preparing for letsencrypt ...
[2018-03-14 00:25:25] Starting letsencrypt verification
Already up-to-date.
Parsing account key...
Parsing CSR...
Registering account...
Already registered!
Verifying seafile.link15.de...
Traceback (most recent call last):
  File "/shared/ssl/letsencrypt/acme_tiny.py", line 198, in <module>
    main(sys.argv[1:])
  File "/shared/ssl/letsencrypt/acme_tiny.py", line 194, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca)
  File "/shared/ssl/letsencrypt/acme_tiny.py", line 123, in get_crt
    wellknown_path, wellknown_url))
ValueError: Wrote file to /var/www/challenges/HY8vyXX7cRndr1JZ3wqylNUjQnSoE9_O_0ovdC3dN_4, but couldn't download http://seafile.link15.de/.well-known/acme-challenge/HY8vyXX7cRndr1JZ3wqylNUjQnSoE9_O_0ovdC3dN_4
Traceback (most recent call last):
  File "/scripts/bootstrap.py", line 196, in <module>
    main()
  File "/scripts/bootstrap.py", line 185, in main
    init_letsencrypt()
  File "/scripts/bootstrap.py", line 67, in init_letsencrypt
    call('/scripts/ssl.sh {0} {1}'.format(ssl_dir, domain))
  File "/scripts/utils/__init__.py", line 68, in call
    return subprocess.check_call(*a, **kw)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/scripts/ssl.sh /shared/ssl seafile.link15.de' returned non-zero exit status 1
`

Any help on that? HTTP works fine, HTTPS dont.. The Certs are created in shared/ssl but https connection is not working

**Comment by Meerbi** [comment]
`ValueError: Wrote file to /var/www/challenges/IUvvUS3KOWILPYm5fT33xYOE6ufZjUPJ9uEFNDWYUYY, but couldn't download http://link15.de/.well-known/acme-challenge/IUvvUS3KOWILPYm5fT33xYOE6ufZjUPJ9uEFNDWYUYY
`

I'm using.
Fresh Install of Centos 7
Fresh Install of Docker
yum update -- All Updates
Nothing more installed
I installed the Docker Image of Sealfile exactly like the instructions

Domain Record is ok. Verifying over Certbot works like a Charm. But not with the Image.

Shitty Script.

**Comment by freeplant** [comment]
Please try the latest version. `launcher` is no longer used.

**Comment by MJPA** [comment]
Getting the same thing. Using a docker-compose.yml that is:

        version: '3'

    services:
      seafile:
        image: seafileltd/seafile:latest
        volumes:
          - ./shared:/shared
        ports:
          - 443:443
          - 80:80
        environment:
          - SEAFILE_SERVER_LETSENCRYPT=true
        env_file:
          - seafile.env
        restart: always

**Comment by MJPA** [comment]
@freeplant looks like you just need to pass `--disable-check` to the letsencrypt script?

The check can obviously fail inside a docker container when the actual request would succeed. Disabling the check in the script itself lets the cert generate successfully...

**Comment by zMingGit** [comment]
@MJPA  you need provide a domain name if you want enable https, and ensure that domain name already resolved to this server.

**Comment by zMingGit** [comment]
@MJPA  can you show your seafile.env file?

**Comment by MJPA** [comment]
@zMingGit 

With values changed:

    SEAFILE_SERVER_HOSTNAME=seafile.example.com
    SEAFILE_ADMIN_EMAIL=admin@example.com
    SEAFILE_ADMIN_PASSWORD=adminpass

The hostname resolves fine - for some reason the docker container can't access the external IP of the host. There is something to do with the image that is stopping it working - other containers on the same host can access the host fine.

**Comment by MJPA** [comment]
Installed ping in the container, I can `ping seafile.example.com` and get a response, but `curl http://seafile.example.com` gives `No route to host` - it gets the right IP though.

**Comment by zMingGit** [comment]
@MJPA  you need to change `seafile.example.com` to your domain name, and ensure the domain name has resolved to this server.

**Comment by MJPA** [comment]
@zMingGit what? That's an example... the domain name that's actually in my env file resolves to the host's external IP. The issue is the container cannot access port 80 of the external IP of the host.

**Comment by MJPA** [comment]
Not sure if it's CentOS (and similar) specific or not, but containers can't access ports that are normally closed on the firewall.

Default firewalld config only has SSH open. Docker opens the ports that are mapped to containers, so the above `docker-compose.yml` will open up ports 80 and 443 but they're only open from the outside world to the containers. The container itself, cannot access the ports. Running `firewall-cmd --add-service=http --permanent` fixes this... might be worth adding to the readme somewhere?

**Comment by zMingGit** [comment]
@MJPA  OK, thanks for your advice.
