### ISSUE TITLE
Docker Hub

### ISSUE THREAD

**Issue by jpsikorra** [haiwen/seafile-docker#5]
Why is this not on Docker Hub?

**Comment by yangxuan8282** [comment]
agree, it would be convenient if put on docker hub

**Comment by lins05** [comment]
It is on docker hub, check https://hub.docker.com/r/seafileorg/server/

This repository contains both the files/scripts to build the image, and, more importantly, some scripts to ease the management of the seafile server like upgrading. The users (especially those less familiar with docker) also don't need to interact with docker directly by using the launcher script.
