### ISSUE TITLE
Migration from launcher 

### ISSUE THREAD

**Issue by sascha-schieferdecker** [haiwen/seafile-docker#50]
The commands for the migration are not working, because the image is not published. Also you have to mount some more directories to get the container working, e.g for my configuration behind a proxy:

```
docker run -d --restart=always --name seafile -h seafile -v /var/seafile/shared:/shared -v /var/seafile/shared/logs/var-log:/var/log -v /var/seafile/shared/db:/var/lib/mysql -v /var/seafile/shared/.bash_history:/root/.bash_history -p 127.0.0.1:81:80 local_seafile/server:latest
```

**Comment by zMingGit** [comment]
In the latest version you can use `-v /var/seafile/shared:/shared` instead of `-v /var/seafile/shared:/shared -v /var/seafile/shared/logs/var-log:/var/log -v /var/seafile/shared/db:/var/lib/mysql`. Before this, i recommand you do backup.
