### ISSUE TITLE
can't upload and download any files

### ISSUE THREAD

**Issue by JordanChenCN** [haiwen/seafile-docker#52]
### ERROR
![tim 20180420144404](https://user-images.githubusercontent.com/20235070/39034738-11e2291e-44aa-11e8-9814-ba65fcda2bde.png)

**Comment by zMingGit** [comment]
Is it normal to upload files through the web interface?

**Comment by JordanChenCN** [comment]
can't upload files through the web interface too.

**Comment by shoeper** [comment]
Closing this due to lack of feedback.
