### ISSUE TITLE
Probleam restarting container

### ISSUE THREAD

**Issue by ivbeg** [haiwen/seafile-docker#57]
I've installed seafile docker with

> docker run -d --name seafile -e SEAFILE_SERVER_HOSTNAME=files.begtin.tech -v /opt/seafile-data:/shared -p 3080:80 seafileltd/seafile:latest

after restart I've got this in log

*** Killing all processes...
*** Running /etc/my_init.d/01_create_data_links.sh...
ln: /opt/seafile/seahub-data: cannot overwrite directory
*** /etc/my_init.d/01_create_data_links.sh failed with status 1

*** Killing all processes...

**Comment by QiaoBangZhu** [comment]
I also have  the this problem.

**Comment by zMingGit** [comment]
Which way did you restart. it's work for me.

**Comment by zMingGit** [comment]
it's already fixed. please pull latest image and try again.
