### ISSUE TITLE
安装成功之后  使用docker restart seafile 重启失败

### ISSUE THREAD

**Issue by QiaoBangZhu** [haiwen/seafile-docker#59]
*** Init system aborted.
*** Killing all processes...
*** Running /etc/my_init.d/01_create_data_links.sh...
ln: /opt/seafile/seahub-data: cannot overwrite directory
*** /etc/my_init.d/01_create_data_links.sh failed with status 1
*** Killing all processes...
*** Running /etc/my_init.d/01_create_data_links.sh...
ln: /opt/seafile/seahub-data: cannot overwrite directory
*** /etc/my_init.d/01_create_data_links.sh failed with status 1
*** Killing all processes...

**Comment by zMingGit** [comment]
Which version do you use?  please try use seafileltd/seafile:latest again.

**Comment by QiaoBangZhu** [comment]
今天刚刚重新安装的呢 还是不行

**Comment by zMingGit** [comment]
Which version do you use?

**Comment by QiaoBangZhu** [comment]
REPOSITORY                     TAG                 IMAGE ID            CREATED             SIZE
docker.io/seafileltd/seafile   latest              c2eaae9d6e34        4 weeks ago         817 MB
docker.io/jenserat/seafile     latest              58e51472627c        2 months ago        297 MB

**Comment by zMingGit** [comment]
Your image is out of date.  please download seafileltd/seafile:latest again.

**Comment by QiaoBangZhu** [comment]
哦哦 好的  可能是我不太了解docker ,请问我该如何更新最新版本呢？我现在删除了旧版本重新安装也是无法更新到最新版

**Comment by QiaoBangZhu** [comment]
知道如何操作了。我使用 docker pull seafileltd/seafile:latest 下载了最新版
 docker.io/seafileltd/seafile   latest              7e8327257e54        2 days ago          817 MB 
这个版本还是重启失败

**Comment by zMingGit** [comment]
我无法重现，请提供详细的操作步骤，以及系统信息.

**Comment by QiaoBangZhu** [comment]
Linux version 3.10.0-693.21.1.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) )
docker ps -a 查看显示如下：
3c0afb3c138c        c2eaae9d6e34        "/sbin/my_init -- ..."   3 hours ago         Exited (1) 3 seconds ago                       seafile
使用docker start seafile或者docker restart seafile 均无法启动. 只有使用 docker rm -f 3c0afb3c138c 删除 docker images,重新安装 才能启动成功，然后 再次重启 还是停止了之后启动不了。

**Comment by zMingGit** [comment]
3c0afb3c138c c2eaae9d6e34 "/sbin/my_init -- ..." 3 hours ago Exited (1) 3 seconds ago seafile.

c2eaae9d6e34
You're still using the old image!!!!

**Comment by BerdyPango** [comment]
Hey I met the same problem when I issue docker run ... in my  raspbian OS, I'm sure it is the latest version, do you have some clue? Here's some information for your reference:
REPOSITORY                                 TAG                 IMAGE ID            CREATED             SIZE
seafileltd/seafile                         latest              d4825fe325c2        3 weeks ago         900MB

CONTAINER ID        IMAGE                                             COMMAND                  CREATED             STATUS                     PORTS               NAMES
c678387b75eb        seafileltd/seafile:latest                         "/sbin/my_init -- /s…"   12 seconds ago      Exited (1) 9 seconds ago

**Comment by QiaoBangZhu** [comment]
my Seafile image is 7e8327257e54 817MB,please confirm your Seafile image is latest. then reinstall it.

**Comment by BerdyPango** [comment]
I get the image after I issue the cmd from the instruction page. I believe it should be the latest image, isn’t it? If not, how am I supposed to get the latest image?
