### ISSUE TITLE
LDAP SSL doesn't work

### ISSUE THREAD

**Issue by theasp** [haiwen/seafile-docker#61]
LDAP SSL doesn't work in the docker image, resulting in "Can't contact LDAP server". This problem is probably caused by this issue: https://github.com/haiwen/seafile/issues/1774

**Comment by shoeper** [comment]
@zMingGit

**Comment by shoeper** [comment]
@zMingGit

**Comment by shoeper** [comment]
@freeplant

**Comment by skliarie** [comment]
The problem still exists, please reopen it.

**Comment by freeplant** [comment]
As we tested, LDAPS works in the latest docker image. The original problem was caused by using Seafile CentOS package on Ubuntu image, which was resolved a few months ago.

I think your problem is that you are using an invalid CA.
