### ISSUE TITLE
How to parameterise `client_max_body_size`

### ISSUE THREAD

**Issue by yatesco** [haiwen/seafile-docker#62]
`client_max_body_size` is set to 10m in https://github.com/haiwen/seafile-docker/blob/9c3fdcae32008cf7a8a45bbd20b1204823a5820e/image/seafile/templates/seafile.nginx.conf.template#L31.

I couldn't see how to parameterise it, which seems odd as this is a pretty big restriction.

Could you please make it parameterisable and/or set it to a much more reasonable number than 10MB.

Thanks!

**Comment by shoeper** [comment]
I think it should be zero instead, given that I expect that in most cases there will be a proxy on the host.

**Comment by yatesco** [comment]
Can I run Nginx on the host and proxy forward to Seafile in the container? Wouldn’t the container still run Nginx inside?

**Comment by shoeper** [comment]
I've just checked it and the client_max_body_size is actually being set to zero in the more specific location parts. Uploads go through /seafhttp or /seafdav (WebDAV) so there shouldn't be any issue.
