### ISSUE TITLE
How to start seafile again

### ISSUE THREAD

**Issue by GITchristoph** [haiwen/seafile-docker#67]
Rather a beginner question than a real issue I guess. 

I followed the manual and the seafile docker image started. 
I could login with an admin user.

I then stopped the seafile docker image
> docker stop seafile

How can I start it again now?

The initial code

> docker run -d --name seafile \
>   -e SEAFILE_SERVER_HOSTNAME=seafile.example.com \
>   -e SEAFILE_ADMIN_EMAIL=me@example.com \
>   -e SEAFILE_ADMIN_PASSWORD=a_very_secret_password \
>   -v /opt/seafile-data:/shared \
>   -p 80:80 \
>   seafileltd/seafile:latest

gives the error:

> docker: Error response from daemon: Conflict. The container name "/seafile" is already in use by container "d083bda8da18d2524bddcdb22c7118830ab80a8834fb4c97b74cebd47c5ca4c0". You have to remove (or rename) that container to be able to reuse that name.

**Comment by shoeper** [comment]
It is unlikely that this is a bug. Use the [forum](https://forum.seafile.com/) for questions, please.

docker start seafile
