### ISSUE TITLE
Docker image isn't honoring custom media folder

### ISSUE THREAD

**Issue by tafoya** [haiwen/seafile-docker#69]
Within seahub_settings.py, I have set a custom media folder MEDIA_URL = '/seafmedia/' as specified in the manual (https://manual.seafile.com/deploy/deploy_seahub_at_non-root_domain.html). The docker image doesn't use the config for the custom media folder. I can change the nginx config inside the container, but it reverts on every restart of the container.

**Comment by shoeper** [comment]
Yes, you're changes are not persisted and thus removed when stopping your docker container.
