### ISSUE TITLE
Upgrade from 6.0.5 to 6.0.7 hangs

### ISSUE THREAD

**Issue by ks1962** [haiwen/seafile-docker#7]
Hi all,

I run the 6.0.5 version for a month without any problems. 
Now I tried the upgrade with "./launcher rebuild" and after a while the message "Now building the local docker image." appears. From now on the CPU is busy with about 20% and the disk fills, but nothing else happens. After an hour or so I canceled the script before the disk was full. There is nothing to see in the system logs, the new image is correctly pulled but no new container is build.
Obviously it is the command "docker build -f bootstrap/generated/Dockerfile -t local_seafile/server:latest  . >/dev/null" that loops(?) and I have noticed that the new Dockerfile differs from the prevoius:

_6.0.7
...
RUN cp -rp /app/scripts /scripts && \
    cp -rp /app/bootstrap /bootstrap && \
   cp /app/bootstrap/generated/seafile.nginx.conf /etc/nginx/sites-enabled/seafile.nginx.conf

6.0.5
...
RUN cp -rp /app/scripts /scripts && \
    cp -rp /app/bootstrap /bootstrap && \
    **cp /app/scripts/tmp/check_init_admin.py /opt/seafile/seafile-server-6.0.5/check_init_admin.py && \**
   cp /app/bootstrap/generated/seafile.nginx.conf /etc/nginx/sites-enabled/seafile.nginx.conf_

Can anyone help?
Thanks!

**Comment by lins05** [comment]
What's your linux distro and docker version? You can check it by running `docker version`.

I have just tried upgrading from 6.0.5 to 6.0.7 on ubuntu 14.04 with docker 1.10.3, and it works smoothly. From your description I don't tell what happened. Can you try to run `./launcher rebuild -v`? The `-v` flag would make it output more debug messages.

> and I have noticed that the new Dockerfile differs from the prevoius:

That's correct, we had some patch for seafile server scripts of 6.0.5 in this repo, which is already merged into 6.0.7. That's why you see there is one less line in the Dockerfile of 6.0.7. I don't think this is related to your problem.

**Comment by ks1962** [comment]
Linux distro is vmware Photon 1.0, Docker version is 1.12.1
I already used the -v flag, but there was nothing interesting to see. The hang happens with the command "docker build .." and this shows no output.

**Comment by lins05** [comment]
I have tried it on a clean vmware phonto virtual machine, but the upgrade still works good for me. So I guess this is related to your specific environment.

**Comment by ks1962** [comment]
o.k thank you, I will try again with a different VM

**Comment by ks1962** [comment]
Problem solved!

My seafile directory resides on a nfs share of a netapp filer. Beside the data there is always a .snapshot directory present, that holds all snapshots (=all data multiplied with the number of snapshots)
Now in the dockerfile used for the build command is a statement „ADD . /app“ that copies everything from the current directory (inclusive .snapshot!) to the new container - and there are a lot of gigabytes! So the docker build commands is running for a very long time and the disk space fills.

Solution:
I added .snapshot/* to the .dockerignore file – everything is fine now.
It would be helpful if you can add this exclusion to the original .dockerignore to avoid this problem for a fresh install or when you update the .dockerignore file in new image.

**Comment by lins05** [comment]
Done. Thanks for reporting this.

**Comment by ks1962** [comment]
Thank you very much!
