### ISSUE TITLE
LETSENCRYPT Automatic renew of certificate 

### ISSUE THREAD

**Issue by c00kie55** [haiwen/seafile-docker#78]
Hi iam using this config an its working but does it automatic renew the certificate ?

docker run -d --name seafile \
  -e SEAFILE_SERVER_LETSENCRYPT=true \
  -e SEAFILE_SERVER_HOSTNAME=seafile.example.com \
  -e SEAFILE_ADMIN_EMAIL=me@example.com \
  -e SEAFILE_ADMIN_PASSWORD=a_very_secret_password \
  -v /opt/seafile-data:/shared \
  -p 80:80 \
  -p 443:443 \
  seafileltd/seafile:latest

**Comment by Maurotb** [comment]
same problem, how to renew certificate?

**Comment by akomm** [comment]
I have noticed, sadly, it does only check certificate on startup, so when you restart the container it should trigger. Not sure, why making own init script and have cron running, but not renewing certificates. Maybe a bug.

**Comment by k-rloss** [comment]
as a workaround I'm updating the  _domain_.crt file on my end, and placing the updated file under /opt/seafile-data/ssl
(Making sure that the _domain_.crt file contains both the signed cert block, as well as the intermediate cert. Simply concatenate both crt files)


Then I simply restart the docker container:
`docker container restart seafile`

**Comment by meldron** [comment]
As a work around I call the `ssl.sh` script manually within the container:

 `./ssl.sh /shared/ssl/ domain.com`
