### ISSUE TITLE
Nginx Proxy

### ISSUE THREAD

**Issue by Kerwood** [haiwen/seafile-docker#8]
Okay, need some help here.. I just spend the last 3 hours trying ti figure this out and tried anything I could think about.

I want to use my Nginx Proxy to proxy connections to the Seafile container.
Nginx redirects from port 80 to 443.
Nginx has the SSL certificates.

No matter what I try, I cant figure it out. Help me here mate.

**Comment by Kerwood** [comment]
It works just fine if I dont use the Nginx Proxy.
But even if i turn SSL off in the proxy, Seafile is still redirecting me to https ?!..

**Comment by akomm** [comment]
its a bit late, but for those who have the same issue...

If your nginx server has the certificate and not seafile, you should not map to seafile 443.

My seafile is configured 127.0.0.1:10000:80 (mapping) 
And nginx is proxy 443 -> 127.0.0.1:10000

Then after "bootstrap" and "start", when shared/conf/seahub_settings.py is generated, modify the URL under "FILE_SERVER_ROOT" from http to https
