### ISSUE TITLE
How to set proper reverse proxy?

### ISSUE THREAD

**Issue by nachopro** [haiwen/seafile-docker#83]
Hi All, I'm a newcomer.
I have a little issue, when I access to the `Devices` section I see a wrong IP for all them. The IP showed is from the internal container, not from the real client.

I missed a setting? Thanks

![sea](https://user-images.githubusercontent.com/260549/42640596-084cdce0-85c9-11e8-8163-d61adf398279.png)

I started my container with this line:
```bash
docker run -d
           --name seafile 
           -e SEAFILE_SERVER_HOSTNAME=my.secret.domain 
           -v /mnt/raid/seafile-data:/shared
           -p 8080:80 seafileltd/seafile:latest
```

Here is my local nGinx's VirtualHost

```nginx
server {
    server_name my.secret.domain;
    listen 443;

    access_log /var/log/nginx/my.secret.domain.access main;
    error_log /var/log/nginx/my.secret.domain.error info;

    client_max_body_size 10G;

    ssl on;
    ssl_certificate /etc/letsencrypt/live/my.secret.domain/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/my.secret.domain/privkey.pem;
    include snippets/ssl_secure.conf;

    location / {
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        add_header Front-End-Https on;

        proxy_connect_timeout       300;
        proxy_send_timeout          300;
        proxy_read_timeout          300;
        send_timeout                300;

        proxy_pass http://127.0.0.1:8080;
    }
}
```

**Comment by nachopro** [comment]
Well, I exposed the internal ports bypassing the internal container's nginx.
Thanks!

**Comment by zwnk** [comment]
i'm facing the same issue. some can give me a hint? :)

**Comment by nachopro** [comment]
@zwnk I'm running my container with ```-p 8080:8080 -p 8082:8082``` and using whis nginx [0] with ```proxy_pass http://127.0.0.1:8080;```

[0] https://manual.seafile.com/deploy/deploy_with_nginx.html

**Comment by zwnk** [comment]
> @zwnk I'm running my container with `-p 8080:8080 -p 8082:8082` and using whis nginx [0] with `proxy_pass http://127.0.0.1:8080;`
> 
> [0] https://manual.seafile.com/deploy/deploy_with_nginx.html

with this ports i get a bad gateway.
if i use -p 8080:**8000** -p 8082:8082 and use the 
`proxy_pass http://127.0.0.1:8080` for the `location /` and `proxy_pass http://127.0.0.1:8082`  for `location /seafilehttp` the server runs and is see external ip addresses for the devices. nethertheless they can't connect.
i can't find any hint at the logs. the android client says Forbidden.
