### ISSUE TITLE
Support sqlite

### ISSUE THREAD

**Issue by languitar** [haiwen/seafile-docker#89]
I have an existing installation of seafile that is using sqlite. I'd like to move this to a docker-based installation but the existing image doesn't allow sqlite as the database backend and there seems to be no data migration script.

**Comment by wucke13** [comment]
Do the database migration yourself. I did it, but from `mariadb` to the dockerized system. Its fairly easy though.
Dumping from `sqlite` db is up to you - once you've done that, take a close look at the chapter "Backup and Recovery" in the Seafile manual (https://manual.seafile.com/deploy/deploy_with_docker.html#backup-and-recovery). There is a detailed tutorial on how to insert the backups (`.sql` files) into the docker image.

Regarding the request, I do not see a need for a script. It is barely likely that someone is doing the migration more then once, and for one time doing the dump and inserting it manually should be fine.
