### ISSUE TITLE
Unable to change the logo using the latest docker image

### ISSUE THREAD

**Issue by fjtc** [haiwen/seafile-docker#90]
When you try to change the logo using the docker image (seafileltd/seafile:latest d4825fe325c2) an internal server error message is issued and nothing happens.

Inside the seahub.log, it is possible to see entries like:
- `[ERROR] seahub.api2.endpoints.admin.logo:64 post [Errno 17] File exists`

After a brief investigation, I found out that the problem is caused by the fact that the directory `/opt/seafile/seahub-data` is not a link to `/shared/seafile/seahub-data` like others but an actual directory that contains 2 entries:

- avatars: (a soft link to `/shared/seafile/seahub-data/avatars`);
- custom: a directory with mylogo.png but with the incorrect permissions;

The incorrect rights inside custom was preventing the file from being replaced. This should also prevent the files from `custom` to be migrated correctly when the container is destroyed because it is outside the `/shared `.

I solved this issue inside the container by performing the following steps:

1. Move `/opt/seafile/seahub-data/custom` to `/shared/seafile/seahub-data/custom`
1. Set the owner of `/shared/seafile/seahub-data/custom` to the same owner of `/shared/seafile/seahub-data/avatars`;
1. Delete the directory `/opt/seafile/seahub-data` and replace it by a soft link to `/shared/seafile/seahub-data`;

This procedure worked well but it is not permanent because it is not permanent. Is it possible to integrate this fix into the next release of the docker image?

**Comment by lins05** [comment]
Thanks for reporting! We'll try to reproduce & fix it.

**Comment by lins05** [comment]
Actually this is not a bug of permission, rather some subtle logic bug in the `scripts/create_data_links.sh` script. If you already have a seafile container running, simply do a `docker restart seafile` would allow you to upload custom logos without any problem.

It is now fixed in https://github.com/haiwen/seafile-docker/commit/1a6d11ff62cf3b18014cb38d71276c748ca7ccb2 so new users would not encounter that again.
