### ISSUE TITLE
maintenance mode

### ISSUE THREAD

**Issue by shoeper** [haiwen/seafile-docker#93]
It looks like some things to require stopping seafile.

Because the start script does exit when seafile stopped the containers also exits. It would be helpful to have some maintenance mode. This could be implemented by simply checking if a file exists. E.g. if /maintenance exists start.py does not exit. On start I'd implement and document that the maintenance file gets removed if it exists. This effectively prevents forgetting to remove it.

**Comment by lins05** [comment]
You can start another container with different CMD to do any maintenance work, e.g.

```sh
docker run -it --name seafile-debug \
  -v /opt/seafile-data:/shared \
  seafileltd/seafile:latest /sbin/my_init -- bash -i
```

**Comment by shoeper** [comment]
Yes, that's correct. It could be more complicated though when using other tools than the command line as it requires creating a new container.
